export const SUNSET_SUNRISE_API = "https://api.sunrise-sunset.org/json"
export const CITIES_GEO_LOCATION_API = "https://raw.githubusercontent.com/Kaosc/cities-geo-location-api/master/cities.json"
export const SUNSET_SUNRISE_WEB = "https://sunrise-sunset.org/"
export const LOGO_URL = "https://raw.githubusercontent.com/Kaosc/sunset-sunrise-extension/main/public/assets/icon512.png"
export const GITHUB_REPO = "https://github.com/kaosc/sunset-sunrise-extension"