export const SUNSET_SUNRISE_API = "https://api.sunrise-sunset.org/json"
export const CITIES_GEO_LOCATION_API = "https://raw.githubusercontent.com/Kaosc/cities-geo-location-api/master/cities.json"
export const SUNSET_SUNRISE_WEB = "https://sunrise-sunset.org/"
export const GITHUB_REPO = "https://github.com/kaosc/sunset-sunrise-extension"
export const WEB_STORE_URL = "https://chrome.google.com/webstore/detail/sunset-sunrise/gkfelccnlfiipepkjfmgbkaebppelfma"